/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package opsapp;

/**
 *
 * @author 26tirusaan
 */
public class OppsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OppsFrame
     */
    public OppsFrame() {
        initComponents();  
    }

      int one;
      int two;
      int sum;
      
      double one1;
      double two1;
      double sum1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        IntLabel = new javax.swing.JLabel();
        DeltaLabel = new javax.swing.JLabel();
        DeltaField = new javax.swing.JTextField();
        IntField1 = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JButton();
        MultiplyButton = new javax.swing.JButton();
        ModButton = new javax.swing.JButton();
        DivideButton = new javax.swing.JButton();
        PowerButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        IntByeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DoubleDivideButton = new javax.swing.JButton();
        DoublePowButton = new javax.swing.JButton();
        DoubleClearButton = new javax.swing.JButton();
        DoubleByeButton = new javax.swing.JButton();
        DoubleLabel = new javax.swing.JLabel();
        DeltaLabel1 = new javax.swing.JLabel();
        DoubleDeltaField = new javax.swing.JTextField();
        DoubleField = new javax.swing.JTextField();
        DoubleAddButton = new javax.swing.JButton();
        DoubleMinusButton = new javax.swing.JButton();
        DoubleMultiplyButton = new javax.swing.JButton();
        DoubleModButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 0, 204));

        IntLabel.setBackground(new java.awt.Color(102, 102, 102));
        IntLabel.setForeground(new java.awt.Color(0, 0, 0));
        IntLabel.setText("                    Integer");

        DeltaLabel.setBackground(new java.awt.Color(102, 102, 102));
        DeltaLabel.setForeground(new java.awt.Color(0, 0, 0));
        DeltaLabel.setText("                    Delta");

        DeltaField.setBackground(new java.awt.Color(255, 255, 0));
        DeltaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeltaFieldActionPerformed(evt);
            }
        });

        IntField1.setBackground(new java.awt.Color(102, 255, 51));
        IntField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntField1ActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(216, 72, 33));
        AddButton.setForeground(new java.awt.Color(0, 0, 0));
        AddButton.setText("+=");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        MinusButton.setBackground(new java.awt.Color(216, 72, 33));
        MinusButton.setForeground(new java.awt.Color(0, 0, 0));
        MinusButton.setText("-=");
        MinusButton.setActionCommand("jButton2");
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });

        MultiplyButton.setBackground(new java.awt.Color(216, 72, 33));
        MultiplyButton.setForeground(new java.awt.Color(0, 0, 0));
        MultiplyButton.setText("x=");
        MultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyButtonActionPerformed(evt);
            }
        });

        ModButton.setBackground(new java.awt.Color(216, 72, 33));
        ModButton.setForeground(new java.awt.Color(0, 0, 0));
        ModButton.setText("%=");
        ModButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModButtonActionPerformed(evt);
            }
        });

        DivideButton.setBackground(new java.awt.Color(216, 72, 33));
        DivideButton.setForeground(new java.awt.Color(0, 0, 0));
        DivideButton.setText("/=");
        DivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideButtonActionPerformed(evt);
            }
        });

        PowerButton.setBackground(new java.awt.Color(216, 72, 33));
        PowerButton.setForeground(new java.awt.Color(0, 0, 0));
        PowerButton.setText("POW");
        PowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("ClearButton");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        IntByeButton.setText("ByeButton");

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));

        DoubleDivideButton.setBackground(new java.awt.Color(216, 72, 33));
        DoubleDivideButton.setText("/=");
        DoubleDivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleDivideButtonActionPerformed(evt);
            }
        });

        DoublePowButton.setBackground(new java.awt.Color(216, 72, 33));
        DoublePowButton.setText("POW");
        DoublePowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoublePowButtonActionPerformed(evt);
            }
        });

        DoubleClearButton.setText("ClearButton");
        DoubleClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleClearButtonActionPerformed(evt);
            }
        });

        DoubleByeButton.setText("ByeButton");

        DoubleLabel.setBackground(new java.awt.Color(102, 102, 102));
        DoubleLabel.setForeground(new java.awt.Color(0, 0, 0));
        DoubleLabel.setText("                    Double");

        DeltaLabel1.setBackground(new java.awt.Color(102, 102, 102));
        DeltaLabel1.setForeground(new java.awt.Color(0, 0, 0));
        DeltaLabel1.setText("                    Delta");

        DoubleDeltaField.setBackground(new java.awt.Color(255, 255, 0));
        DoubleDeltaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleDeltaFieldActionPerformed(evt);
            }
        });

        DoubleField.setBackground(new java.awt.Color(102, 255, 51));
        DoubleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleFieldActionPerformed(evt);
            }
        });

        DoubleAddButton.setBackground(new java.awt.Color(216, 72, 33));
        DoubleAddButton.setText("+=");
        DoubleAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleAddButtonActionPerformed(evt);
            }
        });

        DoubleMinusButton.setBackground(new java.awt.Color(216, 72, 33));
        DoubleMinusButton.setText("-=");
        DoubleMinusButton.setActionCommand("jButton2");
        DoubleMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleMinusButtonActionPerformed(evt);
            }
        });

        DoubleMultiplyButton.setBackground(new java.awt.Color(216, 72, 33));
        DoubleMultiplyButton.setText("x=");
        DoubleMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleMultiplyButtonActionPerformed(evt);
            }
        });

        DoubleModButton.setBackground(new java.awt.Color(216, 72, 33));
        DoubleModButton.setText("%=");
        DoubleModButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleModButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DoubleDeltaField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DoubleField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DoubleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DeltaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DoubleClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DoubleByeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DoubleDivideButton)
                                    .addComponent(DoubleAddButton))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DoubleMinusButton)
                                    .addComponent(DoubleModButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DoubleMultiplyButton)
                                    .addComponent(DoublePowButton))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(DoubleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoubleField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(DeltaLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoubleDeltaField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoubleAddButton)
                    .addComponent(DoubleMinusButton)
                    .addComponent(DoubleMultiplyButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoubleModButton)
                    .addComponent(DoubleDivideButton)
                    .addComponent(DoublePowButton))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoubleClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoubleByeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DeltaField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IntField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(IntLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(DeltaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IntByeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DivideButton)
                                    .addComponent(AddButton))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MinusButton)
                                    .addComponent(ModButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MultiplyButton)
                                    .addComponent(PowerButton))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(IntLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IntField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(DeltaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeltaField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(MinusButton)
                    .addComponent(MultiplyButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModButton)
                    .addComponent(DivideButton)
                    .addComponent(PowerButton))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntByeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideButtonActionPerformed
      
        one = Integer.parseInt(IntField1.getText());
        two = Integer.parseInt(DeltaField.getText());
        sum = one/two;             
    if(DeltaField.equals("0")){
        DeltaField.setText("Cannot divide by 0 stupid"); 
    }else{                      
        IntField1.setText(Integer.toString(sum));   
    }
    }//GEN-LAST:event_DivideButtonActionPerformed

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        one = Integer.parseInt(IntField1.getText());
        two = Integer.parseInt(DeltaField.getText());
        sum = one-two;
        IntField1.setText(Integer.toString(sum));
    }//GEN-LAST:event_MinusButtonActionPerformed

    private void DeltaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeltaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeltaFieldActionPerformed

    private void DoubleDivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleDivideButtonActionPerformed

        one1 = Double.parseDouble(DoubleField.getText());
        two1 = Double.parseDouble(DoubleField.getText());
        sum1 = one1/two1;
        if(DoubleDeltaField.equals("0")){
           DoubleDeltaField.setText("Cannot divide by 0 stupid");      
       }else{
            IntField1.setText(Double.toString(sum)); 
        }
    }//GEN-LAST:event_DoubleDivideButtonActionPerformed

    private void DoubleDeltaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleDeltaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleDeltaFieldActionPerformed

    private void DoubleMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleMinusButtonActionPerformed
one1 = Double.parseDouble(DoubleField.getText());
        two1 = Double.parseDouble(DoubleDeltaField.getText());
        sum1 = one1-two1;
        DoubleField.setText(Double.toString(sum));
    }//GEN-LAST:event_DoubleMinusButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        one = Integer.parseInt(IntField1.getText());
        two = Integer.parseInt(DeltaField.getText());
        sum = one+two;
        IntField1.setText(Integer.toString(sum));
    }//GEN-LAST:event_AddButtonActionPerformed

    private void MultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyButtonActionPerformed
        one = Integer.parseInt(IntField1.getText());
        two = Integer.parseInt(DeltaField.getText());
        sum = one*two;
        IntField1.setText(Integer.toString(sum));
    }//GEN-LAST:event_MultiplyButtonActionPerformed

    private void ModButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModButtonActionPerformed
       if(DeltaField.equals("0")){
           DeltaField.setText("Cannot divide by 0 stupid");
       }else{
        one = Integer.parseInt(IntField1.getText());
        two = Integer.parseInt(DeltaField.getText());
        sum = one%two;
        IntField1.setText(Integer.toString(sum));
       }
    }//GEN-LAST:event_ModButtonActionPerformed

    private void PowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButtonActionPerformed
        one = Integer.parseInt(IntField1.getText());
        two = Integer.parseInt(DeltaField.getText());
        sum = (int)Math.pow(one,two);
        IntField1.setText(Integer.toString(sum));
    }//GEN-LAST:event_PowerButtonActionPerformed

    private void DoubleAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleAddButtonActionPerformed
        one1 = Double.parseDouble(DoubleField.getText());
        two1 = Double.parseDouble(DoubleDeltaField.getText());
        sum1 = one1+two1;
        DoubleField.setText(Double.toString(sum));
    }//GEN-LAST:event_DoubleAddButtonActionPerformed

    private void DoubleMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleMultiplyButtonActionPerformed
        one1 = Double.parseDouble(DoubleField.getText());
        two1 = Double.parseDouble(DoubleDeltaField.getText());
        sum1 = one1*two1;
        DoubleField.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleMultiplyButtonActionPerformed

    private void DoubleModButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleModButtonActionPerformed
        if(DoubleDeltaField.equals("0")){
            DoubleDeltaField.setText("Cannot divide by 0 stupid");
        }else{
        one1 = Double.parseDouble(DoubleField.getText());
        two1 = Double.parseDouble(DoubleDeltaField.getText());
        sum1 = one1%two1;
        DoubleField.setText(Double.toString(sum)); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_DoubleModButtonActionPerformed

    private void DoublePowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoublePowButtonActionPerformed
        one1 = Double.parseDouble(DoubleField.getText());
        two1 = Double.parseDouble(DoubleDeltaField.getText());
        sum1 = (int)Math.pow(one1,two1);
        DoubleField.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_DoublePowButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        IntField1.setText("");
        DeltaField.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void IntField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntField1ActionPerformed

    private void DoubleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleFieldActionPerformed

    private void DoubleClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleClearButtonActionPerformed
        DoubleField.setText("");
        DoubleDeltaField.setText("");
    }//GEN-LAST:event_DoubleClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OppsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField DeltaField;
    private javax.swing.JLabel DeltaLabel;
    private javax.swing.JLabel DeltaLabel1;
    private javax.swing.JButton DivideButton;
    private javax.swing.JButton DoubleAddButton;
    private javax.swing.JButton DoubleByeButton;
    private javax.swing.JButton DoubleClearButton;
    private javax.swing.JTextField DoubleDeltaField;
    private javax.swing.JButton DoubleDivideButton;
    private javax.swing.JTextField DoubleField;
    private javax.swing.JLabel DoubleLabel;
    private javax.swing.JButton DoubleMinusButton;
    private javax.swing.JButton DoubleModButton;
    private javax.swing.JButton DoubleMultiplyButton;
    private javax.swing.JButton DoublePowButton;
    private javax.swing.JButton IntByeButton;
    private javax.swing.JTextField IntField1;
    private javax.swing.JLabel IntLabel;
    private javax.swing.JButton MinusButton;
    private javax.swing.JButton ModButton;
    private javax.swing.JButton MultiplyButton;
    private javax.swing.JButton PowerButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
